#!/usr/bin/env node
/**
 * Generate a coverage badge SVG from the vitest coverage summary.
 *
 * GitHub Actions is not running on this repository, so there is no CI step to
 * upload results to a coverage service. This writes a self-contained SVG that
 * the README references, regenerated by `npm run coverage:badge`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const SUMMARY = resolve('coverage/coverage-summary.json');
const OUTPUT = resolve('site/coverage.svg');

let summary;
try {
  summary = JSON.parse(readFileSync(SUMMARY, 'utf8'));
} catch {
  console.error(
    `Could not read ${SUMMARY}.\nRun \`npm run test:coverage\` first.`,
  );
  process.exit(1);
}

const pct = summary.total?.lines?.pct;
if (typeof pct !== 'number') {
  console.error('Coverage summary contained no line percentage.');
  process.exit(1);
}

const rounded = Math.round(pct * 10) / 10;

// Shields.io's colour thresholds, so the badge reads the way people expect.
function colourFor(value) {
  if (value >= 95) return '#4c1';
  if (value >= 90) return '#97ca00';
  if (value >= 75) return '#dfb317';
  if (value >= 60) return '#fe7d37';
  return '#e05d44';
}

const label = 'coverage';
const value = `${rounded}%`;

// Approximate Verdana advance width at 11px, which is what shields.io uses.
const width = (text) => text.length * 6.5 + 10;
const labelWidth = Math.round(width(label));
const valueWidth = Math.round(width(value));
const total = labelWidth + valueWidth;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${total}" height="20" role="img" aria-label="${label}: ${value}">
  <title>${label}: ${value}</title>
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="r"><rect width="${total}" height="20" rx="3" fill="#fff"/></clipPath>
  <g clip-path="url(#r)">
    <rect width="${labelWidth}" height="20" fill="#555"/>
    <rect x="${labelWidth}" width="${valueWidth}" height="20" fill="${colourFor(rounded)}"/>
    <rect width="${total}" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="110" text-rendering="geometricPrecision">
    <text x="${labelWidth * 5}" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="${(labelWidth - 10) * 10}">${label}</text>
    <text x="${labelWidth * 5}" y="140" transform="scale(.1)" textLength="${(labelWidth - 10) * 10}">${label}</text>
    <text x="${(labelWidth + valueWidth / 2) * 10}" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="${(valueWidth - 10) * 10}">${value}</text>
    <text x="${(labelWidth + valueWidth / 2) * 10}" y="140" transform="scale(.1)" textLength="${(valueWidth - 10) * 10}">${value}</text>
  </g>
</svg>
`;

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, svg);

const { statements, branches, functions, lines } = summary.total;
console.log(`Coverage badge written to ${OUTPUT}`);
console.log(
  `  statements ${statements.pct}%  branches ${branches.pct}%  ` +
    `functions ${functions.pct}%  lines ${lines.pct}%`,
);
